apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress-dr
  labels:
    app: wordpress-dr
spec:
  selector:
    matchLabels:
      app: wordpress-dr
      tier: frontend-dr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-dr
        tier: frontend-dr
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress-dr
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          value: Password123!
        ports:
        - containerPort: 80
          name: wordpress-dr
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-import
