apiVersion: v1
kind: Service
metadata:
  name: wordpress-dr
  labels:
    app: wordpress-dr
spec:
  ports:
    - port: 80
      nodePort: 30003
  selector:
    app: wordpress-dr
    tier: frontend-dr
  type: NodePort
