apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress-mysql-dr
  labels:
    app: wordpress-dr
spec:
  selector:
    matchLabels:
      app: wordpress-dr
      tier: mysql-dr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-dr
        tier: mysql-dr
    spec:
      containers:
      - image: mysql:5.6
        name: mysql-dr
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: Password123!
        ports:
        - containerPort: 3306
          name: mysql-dr
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-import
